name: Intrumentation test

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  instrumentation_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11
        cache: gradle
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Run layout tests
      run: |
        ./gradlew pixel5DebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
      env:
        OSSRH_USERNAME: username
        OSSRH_PASSWORD: password
        SIGNING_KEY: signingkey
        SIGNING_KEY_ID: signingkeyid
        SONATYPE_STAGING_PROFILE_ID: profileid
